feat: add junit test and cloverage

diff --git a/.github/workflows/clojure.yml b/.github/workflows/clojure.yml
--- a/.github/workflows/clojure.yml
+++ b/.github/workflows/clojure.yml
@@ -27,6 +27,15 @@ jobs:
       run: make test
     - name: Run generative tests
       run: make test-generative
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v4
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: 'target/junit-*.xml'
+    - name: Publish Coverage Report
+      uses: romeovs/lcov-reporter-action@v0.2.16
+      with:
+        lcov-file: 'target/coverage/lcov.info'
     - name: Run clj-kondo linter
       run: make lint
     - name: Run build jar
